apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: bot
  name: bot-role
rules:
- apiGroups: ["apps","extensions", ""] #   "" indicates the core API group
  resources: ["pods","services","namespaces","deployments/status","jobs","deployments", "events"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete", "status"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bot-rolebinding
  namespace: bot
subjects:
  - kind: ServiceAccount
    name: bot-sa
    namespace: bot
roleRef:
  kind: ClusterRole
  name: bot-role
  apiGroup: rbac.authorization.k8s.io